name: Build Canary with Maximum Optimization

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-optimized:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ilammy/msvc-dev-cmd@v1
        
    - name: Build with Maximum Optimization
      run: |
        clang-cl /EHsc /O2 /Ob2 /Oi /Ot /Oy /fp:fast /GS- /GL /std:c++latest /W4 /MT /DNDEBUG /Fe:Canary.exe Canary.cpp
        
    - uses: actions/upload-artifact@v4
      with:
        name: canary-optimized
        path: Canary.exe